---
title: "pnID_correlations"
format: html
editor: visual
---

```{r}
#| message: false

library (tidyverse)
library(dplyr)
library(ggplot2)
library(ggsignif)
```

```{r Set_Functions}
#| message: false

source("./Functions/perm_test.R") # for perm_test function

couples_function <- function(data,map){
  couples <- 
    combn(map$SampleID, 2) |> 
    data.frame() |> 
    t() |> 
    as.data.frame()

couples$coral <- NA
  for (rown in 1:nrow(couples)) {
    cor2 = cor(data[couples[rown,'V1']]
             , data[couples[rown,'V2']]
             , method = "spearman")
  couples[rown, 'coral'] <- cor2
  }
  return(couples)
}

pnID_function <- function(couples, map){
  map1 <- map |> 
          select(SampleID,pn_ID) |> 
          rename(V1 = SampleID, pnID1 = pn_ID)
  map2 <- map |> 
          select(SampleID,pn_ID) |> 
          rename(V2 = SampleID, pnID2 = pn_ID)
  longcor1 <- couples |> left_join(map1)
  longcor1 <- longcor1 |> left_join(map2)
  
  longcor1 <- longcor1 |> mutate(intrapn = as.character(pnID1 == pnID2))
  longcor1$intrapn <- 
    longcor1$intrapn |> 
    stringr:: str_replace('TRUE','Same subject') |> 
    stringr:: str_replace('FALSE','Different subjects')
  return(longcor1)
}
```

```{r}
#| message: false

Serum_data <- 
  "./Datasets/Serum_metabolomics_dataset.csv" |> read_csv()
Serum_map <- 
  "./Datasets/Serum_metadata.txt" |> read_tsv()

Stool_data <- 
 "./Datasets/Stool_metabolomics_dataset.csv" |> read_csv()
Stool_map <- 
  "./Datasets/Stool_metadata.txt" |> read_tsv()

s16_data <- "./Datasets/16S_dataset.csv" |> read_csv()
s16_map <- "./Datasets/16S_metadata.txt" |> read_tsv()

mgx_ecs <- "./Datasets/MGXecs_dataset.csv" |> read_csv()
mgx_paths <- "./Datasets/MGXpaths_dataset.csv" |> read_csv()
mgx_species <- "./Datasets/MGXspecies_dataset.csv" |> read_csv()
mgx_map <- "./Datasets/MGX_metadata.txt" |> read_tsv()
```

```{r}
#| message: false

Serum_couples <- couples_function(Serum_data,Serum_map)
Stool_couples <- couples_function(Stool_data,Stool_map)
s16_couples <- couples_function(s16_data,s16_map)

mgx_ecs_couples <- couples_function(mgx_ecs,mgx_map)
mgx_paths_couples <- couples_function(mgx_paths,mgx_map)
mgx_species_couples <- couples_function(mgx_species,mgx_map)
```

```{r}
#| message: false

Serum_longcor1 <- 
  pnID_function(Serum_couples,Serum_map) |> mutate(Type = "Serum")
Stool_longcor1 <- 
  pnID_function(Stool_couples,Stool_map) |> mutate(Type = "Stool")
s16_longcor1 <- 
  pnID_function(s16_couples,s16_map) |> mutate(Type = "16S")
mgx_ecs_longcor1 <- 
  pnID_function(mgx_ecs_couples,mgx_map) |> mutate(Type = "mgx_ecs")
mgx_paths_longcor1 <- 
  pnID_function(mgx_paths_couples,mgx_map) |> mutate(Type = "mgx_paths")
mgx_species_longcor1 <- 
  pnID_function(mgx_species_couples,mgx_map) |> mutate(Type = "mgx_species")
```

```{r}
#| message: false

Serum_perm_results <- perm_test(Serum_longcor1)
Stool_perm_results <- perm_test(Stool_longcor1)
s16_perm_results <- perm_test(s16_longcor1)
ecs_perm <- perm_test(mgx_ecs_longcor1)
paths_perm <- perm_test(mgx_paths_longcor1)
species_perm <- perm_test(mgx_species_longcor1)
```

```{r}
#| message: false

intra_perm_results1 <- 
  perm_test(x = Serum_longcor1 |> 
                filter(intrapn == 'Serum_Within') |> 
                select(coral),
            y = Stool_longcor1 |> 
                filter(intrapn == 'Feces_Within') |> 
                select(coral)
            )

intra_perm_results2 <- 
  perm_test(x = Stool_longcor1 |> 
                filter(intrapn == 'Feces_Within') |> 
                select(coral),
            y = s16_longcor1 |> 
                filter(intrapn == '16s_Within') |> 
                select(coral)
            )

inter_perm_results1 <- 
  perm_test(x = Serum_longcor1 |> 
                filter(intrapn == 'Serum_Across')|> 
                select(coral),
            y = Stool_longcor1 |> 
                filter(intrapn == 'Feces_Across')|> 
                select(coral)
            )

mean_perm_results1 <- 
  perm_test(x = Serum_longcor1 |> select(coral),
            y = Stool_longcor1 |> select(coral))

mean_perm_results2 <- 
  perm_test(x = Stool_longcor1 |> select(coral),
            y = s16_longcor1 |> select(coral))
```

```{r}
#| message: false

all_longcor1 <- rbind(Serum_longcor1, Stool_longcor1) |> 
  rbind(s16_longcor1) |> rbind(mgx_ecs_longcor1) |> 
  rbind(mgx_paths_longcor1) |> rbind(mgx_species_longcor1)

all_longcor1 <- all_longcor1 |> 
  mutate(Type = str_replace(Type, "Serum|Stool"
                          , paste0(Type,"\nMetabolomics"))) |> 
  mutate(Type = str_replace(Type, "mgx_","MGX\n"))

all_longcor1$Type <- 
  factor(all_longcor1$Type, 
         levels = c("Serum\nMetabolomics","Stool\nMetabolomics"
                    ,"16S","MGX\nspecies","MGX\necs","MGX\npaths"))
```

```{r}
#| message: false

s_size <- all_longcor1 |> group_by(Type,intrapn) |> 
  summarise(s_size = n())
  
all_longcor1 <- all_longcor1 |> group_by(Type,intrapn) |> 
  mutate(type_n = paste0(intrapn, "\n(n=",n(),")"))
all_longcor1$type_n |> unique()

comp_groups <- all_longcor1 |> group_by(Type,intrapn,type_n) |> 
  summarise()

gnames <- 
  comp_groups |> ungroup() |> group_by(Type) |> 
  summarise(aa=list(type_n)) |> pull(aa)
  
```

```{r}

all_longcor1 |> 
  ggplot(aes(x=type_n, y=coral, fill = intrapn), show.legend = FALSE) + 
  geom_violin(show.legend = FALSE) +
  geom_boxplot(width = .3, show.legend = FALSE) +   
  labs(x = '', y = 'Spearman r') +
  facet_wrap(~Type, nrow = 1, scales = "free_x") +
  # geom_signif(comparisons = list(c("Same subject",
  #                                  "Different subjects")),
  #             map_signif_level = T, textsize =4.5, vjust = 0.5) + 
  theme_bw() + 
    theme(panel.grid = element_blank(),
          plot.background = element_blank(),
          strip.background = element_rect(fill = "white"),
          axis.text = element_text(size=12),
          axis.text.x = element_text(angle = 45,  hjust=1),
          title = element_text(size = 6),
          axis.title = element_text(size = 16),
          strip.text = element_text(size = 14)) 
```

```{r}
#| message: false

ggsave("./R_figures/pnID_Spearman_correlations_boxplots.png",
       height = 4.4, width = 8.5)

```
